package com.kcc.vacation.global.util;


import com.kcc.vacation.domain.employee.dto.response.EmployeeDetail;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.stream.Collectors;

@RequiredArgsConstructor
@Component
public class HtmlUtils {

    public static String generateEmailContent(String joinCodePart1, String joinCodePart2) {
        StringBuilder htmlBuilder = new StringBuilder();

        htmlBuilder.append("<!DOCTYPE html>\n")
                .append("<html xmlns:th=\"http://www.thymeleaf.org\">\n")
                .append("<head>\n")
                .append("  <meta charset=\"UTF-8\">\n")
                .append("  <title>상권 분석 업데이트</title>\n")
                .append("  <style>\n")
                .append("    p {\n")
                .append("      font-size: 18px;\n")
                .append("    }\n")
                .append("    .blue-button {\n")
                .append("      background-color: #007BFF;\n")
                .append("      /* 파란색 */\n")
                .append("      color: white;\n")
                .append("      /* 글자색 흰색 */\n")
                .append("      border: none;\n")
                .append("      /* 테두리 없음 */\n")
                .append("      padding: 10px 20px;\n")
                .append("      /* 여백 */\n")
                .append("      text-align: center;\n")
                .append("      /* 텍스트 가운데 정렬 */\n")
                .append("      text-decoration: none;\n")
                .append("      /* 밑줄 없음 */\n")
                .append("      display: inline-block;\n")
                .append("      /* 인라인 블록으로 배치 */\n")
                .append("      font-size: 16px;\n")
                .append("      /* 글자 크기 */\n")
                .append("      margin: 4px 2px;\n")
                .append("      /* 마진 */\n")
                .append("      cursor: pointer;\n")
                .append("      /* 커서가 손가락 모양으로 변경 */\n")
                .append("      border-radius: 4px;\n")
                .append("      /* 둥근 모서리 */\n")
                .append("      transition: background-color 0.3s;\n")
                .append("      /* 배경색 변화 애니메이션 */\n")
                .append("    }\n")
                .append("    .blue-button:hover {\n")
                .append("      background-color: #0056b3;\n")
                .append("      /* 버튼에 마우스를 올렸을 때 색상 */\n")
                .append("    }\n")
                .append("  </style>\n")
                .append("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\n")
                .append("    integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\n")
                .append("</head>\n")
                .append("<body style=\"font-family: Arial, sans-serif;\">\n")
                .append("  <div class=\"header\" style=\"background-color: #004aad; color: white; padding: 10px; text-align: center;\">\n")
                .append("    <h2>NeoJumper 팀 휴가관리 솔루션에 초대되었습니다.</h2>\n")
                .append("  </div>\n")
                .append("  <div class=\"content\" style=\"margin: 20px; padding: 10px; text-align: center;\">\n")
                .append("    <p>안녕하세요, NeoJumper 팀입니다.</p>\n")
                .append("    <p>NeoJumper 팀에서는 직원분들의 편리한 휴가관리를 위한 솔루션을 제공합니다.</p>\n")
                .append("    <p>저희 팀에 합류하기 위한 인증코드를 보내드립니다.</p>\n")
                .append("    <hr>\n")
                .append("    <h4 style=\"font-weight: bold; color: #828282;\">합류 코드</h4>\n")
                .append("    <h1 style=\"color: #0575E6;\">\n")
                .append("      <strong>")
                .append(joinCodePart1)
                .append("       </strong> - <strong>")
                .append(joinCodePart2)
                .append("      </strong>\n")
                .append("    </h1>\n")
                .append("    <hr>\n")
                .append("    <a href=\"http://localhost:8085/auth/join-form\" style=\"list-style: none;\">\n")
                .append("    <button class=\"blue-button\"> 합류하기</button>\n")
                .append("    </a>\n")
                .append("  </div>\n")
                .append("  <div class=\"footer\" style=\"padding: 10px; text-align: center;\">\n")
                .append("    감사합니다.<br>\n")
                .append("    NeoJumber 인사팀 드림\n")
                .append("  </div>\n")
                .append("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"\n")
                .append("    integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\"\n")
                .append("    crossorigin=\"anonymous\"></script>\n")
                .append("</body>\n")
                .append("</html>");

        return htmlBuilder.toString();
    }

    public static String generateFailNotificationEmailContent(List<EmployeeDetail> resendTargets) {

        StringBuilder htmlBuilder = new StringBuilder();

        htmlBuilder.append("<!DOCTYPE html>\n")
                .append("<html xmlns:th=\"http://www.thymeleaf.org\">\n")
                .append("<head>\n")
                .append("  <meta charset=\"UTF-8\">\n")
                .append("  <title>상권 분석 업데이트</title>\n")
                .append("  <style>\n")
                .append("    p {\n")
                .append("      font-size: 18px;\n")
                .append("    }\n")
                .append("    .blue-button {\n")
                .append("      background-color: #007BFF;\n")
                .append("      /* 파란색 */\n")
                .append("      color: white;\n")
                .append("      /* 글자색 흰색 */\n")
                .append("      border: none;\n")
                .append("      /* 테두리 없음 */\n")
                .append("      padding: 10px 20px;\n")
                .append("      /* 여백 */\n")
                .append("      text-align: center;\n")
                .append("      /* 텍스트 가운데 정렬 */\n")
                .append("      text-decoration: none;\n")
                .append("      /* 밑줄 없음 */\n")
                .append("      display: inline-block;\n")
                .append("      /* 인라인 블록으로 배치 */\n")
                .append("      font-size: 16px;\n")
                .append("      /* 글자 크기 */\n")
                .append("      margin: 4px 2px;\n")
                .append("      /* 마진 */\n")
                .append("      cursor: pointer;\n")
                .append("      /* 커서가 손가락 모양으로 변경 */\n")
                .append("      border-radius: 4px;\n")
                .append("      /* 둥근 모서리 */\n")
                .append("      transition: background-color 0.3s;\n")
                .append("      /* 배경색 변화 애니메이션 */\n")
                .append("    }\n")
                .append("    .blue-button:hover {\n")
                .append("      background-color: #0056b3;\n")
                .append("      /* 버튼에 마우스를 올렸을 때 색상 */\n")
                .append("    }\n")
                .append("  </style>\n")
                .append("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\n")
                .append("    integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\n")
                .append("</head>\n")
                .append("<body style=\"font-family: Arial, sans-serif;\">\n")
                .append("  <div class=\"header\" style=\"background-color: #FF8080; color: white; padding: 10px; text-align: center;\">\n")
                .append("    <h2>메시지 전송 실패</h2>\n")
                .append("  </div>\n")
                .append("  <div class=\"content\" style=\"margin: 20px; padding: 10px; text-align: center;\">\n")
                .append("    <p>안녕하세요, NeoJumper 팀입니다.</p>\n")
                .append("    <p>죄송하지만 시스템 상의 문제로 직원 초대 메일 전송에 실패했습니다.</p>\n")
                .append("    <p>재전송 버튼을 눌러 다시 초대 메일을 전송해주세요!</p>\n")
                .append("    <hr>\n")
                .append("    <h4 style=\"font-weight: bold; color: #828282;\">누락된 직원</h4>\n")
                .append("    <div>\n")
                .append(resendTargets.stream().map(target -> target.getName()).collect(Collectors.joining("<br>\n")))
                .append("    </div>\n")
                .append("    <hr>\n")
                .append("    <a href=\"http://localhost:8085/admin/employee-management?resend=1\" id=\"resendLink\" style=\"list-style: none;\">\n")
                .append("    <button class=\"blue-button\" style=\"background-color: #007BFF; color: white; border: none; padding: 10px 20px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px;\"> 재전송하기</button>\n")
                .append("    </a>\n")
                .append("  </div>\n")
                .append("  <div class=\"footer\" style=\"padding: 10px; text-align: center;\">\n")
                .append("    감사합니다.<br>\n")
                .append("    NeoJumber 인사팀 드림\n")
                .append("  </div>\n")
                .append("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"\n")
                .append("    integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\"\n")
                .append("    crossorigin=\"anonymous\"></script>\n")
                .append("</body>\n")
                .append("</html>");

        return htmlBuilder.toString();
    }
}
